name: Update productive-box

on:
  schedule:
    - cron: '0 0 * * *' # 매일 0시 (KST 9시)에 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # 최신 버전으로 업데이트
      - name: Update productive-box
        uses: gitzip/github-productive-box@main  # 이 부분을 수정했습니다!
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TIMEZONE: Asia/Seoul
